### PR TITLE
feat: Add Cloudflare Environment Variable and Secret support

### PR DESCRIPTION
**Pull request by innovate-invent**
## CloudFlare Environment Variables and Secrets

Support for CloudFlare Environment Variables and Secrets is provided via a wrangler.toml file.
See the [wrangler documentation](https://developers.cloudflare.com/workers/tooling/wrangler/configuration) for more information on the file schema.

To load the wrangler.toml, specify it on the command line:
```shell
$ cloudflare-worker-local /path/to/worker.js localhost:3000 4000 /path/to/wrangler.toml
```

Optionally, the desired environment specified within the wrangler.toml can be loaded:
```shell
$ cloudflare-worker-local /path/to/worker.js localhost:3000 4000 /path/to/wrangler.toml production
```

Secrets are specified under the 'secrets' root key in the document. See the [wrangler.toml](./examples/wrangler.toml) 
for an example of the supported structures.

Two features are provided while loading the wrangler.toml:
* All vars and secrets strings can contain ${} placeholders.
  A placeholder path is resolved using lodash.get and has the context of the root of the config document.
  A placeholder can not refer to a value defined later in the document that also has placeholders.
* Any var or secret that is not a string will be automatically JSON encoded. 
  This allows you to inject complex data into a script by JSON decoding the variable value.

Additionally, any 'kv-namespaces' in the wrangler.toml will be appended to the list of namespaces
provided by KV_NAMESPACES.

### CODE REVIEW

**Comment by gja** [comment]
Actually, I think I misunderstood this PR. It looks like you are replicating the wrangler functionality.

Ok, that’s interesting. Let me think about this.

Do you have any thoughts on doing it this way v/s just including wrangler? This project is older than wrangler, and adding wrangler for config and deploys has been on my task list

**Comment by innovate-invent** [comment]
Wrangler has no means to change its target API endpoint so I don't think we can use wrangler to deploy.
Maybe I am misunderstanding what you mean by deployment. I am using this project as an alternative to hosting the worker on Cloudflare. The cloudflare-worker-local server is the final deployment destination in my mind.

**Comment by innovate-invent** [comment]
I should add, I am using the wrangler.toml file to store the environment variables and secrets because Workers users will likely already have this file written. It made more sense to just reuse the file schema rather than come up with our own way of persisting configuration of the server.

I was thinking of taking this a step further and moving all server config into the wrangler.toml file rather than having a mix of command line arguments, environment variables, and config file.

**Comment by gja** [comment]
Yes, I think that is a good idea. But how would you manage multiple environments? Like a staging and a production setup of the same worker.

**Comment by innovate-invent** [comment]
this commit allows you to specify the target environment on the command line. The wrangler.toml spec already specifies a way of having different environments.

**Pull request merged**
