### PR TITLE
fix(Minio): issue with minio KV triggering undefined error on client.

### PR DESCRIPTION
**Pull request by jdecaron**
Maybe that's just me but I had a few errors trying to run the Minio KV store. Here's a suggested patch.

### CODE REVIEW

**Comment by gja** [comment]
Hi,

Thanks for the PR. What was the issue that you were facing?

**Comment by jdecaron** [comment]
> Hi,
> 
> Thanks for the PR. What was the issue that you were facing?

The issue is described in the title of this pull request and also in the description.

**Comment by jdecaron** [comment]
I will try my best to build you a container that reproduce the error but I am under a work load right now.

**Comment by gja** [comment]
OK, thanks for that. I was hoping for the stack trace at least. In any case, I guess the PR itself looks harmful, so I'll merge it in and release sometime this weekend.

Thanks for the PR!

**Pull request merged**
