### PR TITLE
feat: Add minio KV support

### PR DESCRIPTION
**Pull request by innovate-invent**
This is largely complete except for documentation and an issue with the getClient KVStore interface not supporting concurrency.

If this is an acceptable contribution I will write up the documentation and update the unit tests.

Would changing the getClient interface to async be acceptable?
I have a less ideal workaround involving storing a promise as a object property.

### CODE REVIEW

**Comment by gja** [comment]
Looks good. I’ll merge it in with documentation

**Comment by innovate-invent** [comment]
I have yet to actually test the server as I do not have a minio server configured.
I will be getting to that at some point.

**Comment by gja** [comment]
I think that the way getClient is implemented is fine. And don’t worry too much about tests, you’ll have to mock minio.

Maybe we can set up one integration test on CI that starts a minio docker, but it’s fine for now.

**Comment by innovate-invent** [comment]
I could set up that test on github CI but I am not familiar with azure pipelines.

If you feel this is ready to merge, then please go ahead.

**Pull request merged**
