### PR TITLE
CI

### PR DESCRIPTION
**Pull request by jdanyow**
Uses Azure Pipelines. Runs test suite on node 9, 10 and 11, with linux, mac and windows. Publishes test results and code coverage.

Here's what the integration would look like (tested this on my fork):
- [GitHub PR "conversation" tab](https://github.com/jdanyow/cloudflare-worker-local/pull/2)
- [GitHub PR "checks" tab](https://github.com/jdanyow/cloudflare-worker-local/pull/2/checks)
- [Details on Azure DevOps](https://jdanyow.visualstudio.com/cloudflare-worker-local/_build/results?buildId=9)

Prerequisites:
1. Install azure pipelines from the github marketplace.
    - https://github.com/marketplace/azure-pipelines
    - follow the wizard steps to create a pipeline for gja/cloudflare-worker-local.  It will attempt to create a yml file for you, it's ok to let it create the PR, just close it without merging later.
2. Add branch protection rule for master branch
    https://github.com/gja/cloudflare-worker-local/settings/branch_protection_rules/new
    - [x] Require status checks to pass before merging
    - [x] Include administrators

*note: there's currently [an issue](https://developercommunity.visualstudio.com/content/problem/385331/code-coverage-results-not-rendered-in-build-result.html) preventing the coverage results from displaying in Azure DevOps. I'm sure it will be fixed shortly.*

### CODE REVIEW

**Comment by gja** [comment]
Any reason you picked azure instead of circle CI? I’ve never tried out azure, I guess I’m ok with it, but just curious.

--
Tejas Dinkar
Quintype

**Comment by gja** [comment]
I'm ok with this for now, and I'm setting this up... But I'll intent to move over to Github Actions as soon as I get access :-)

**Comment by gja** [comment]
Any idea why this is failing on windows? https://dev.azure.com/tejas0372/tejas/_build/results?buildId=2

**Comment by jdanyow** [comment]
github actions: :+1: 
why: used circle, travis, etc in the past. currently az pipelines seems to be the fastest/nicest.
full disclosure- I work at msft, however the fact that I'm dabbling with cloudflare workers should make it obvious that I have an open mind when it comes to cloud services :wink: 

looks like the build is failing on windows because of the new crypto dep:
```
2018-11-29T11:04:06.2531781Z npm install
2018-11-29T11:04:06.3117747Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\ef06f6d6-ad05-44df-9b7e-34eb7d3ae979.cmd""
2018-11-29T11:04:45.6043152Z 
2018-11-29T11:04:45.6058042Z > node-webcrypto-ossl@1.0.38 install D:\a\1\s\node_modules\node-webcrypto-ossl
2018-11-29T11:04:45.6166885Z > node-gyp rebuild
2018-11-29T11:04:45.6172067Z 
2018-11-29T11:04:45.6213982Z 
2018-11-29T11:04:45.6239451Z D:\a\1\s\node_modules\node-webcrypto-ossl>if not defined npm_config_node_gyp (node "C:\hostedtoolcache\windows\node\10.14.0\x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\hostedtoolcache\windows\node\10.14.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
2018-11-29T11:04:49.3158382Z gyp ERR! configure error 
2018-11-29T11:04:49.3163502Z gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
2018-11-29T11:04:49.3163763Z gyp ERR! stack   File "<string>", line 1
2018-11-29T11:04:49.3164181Z gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
2018-11-29T11:04:49.3164647Z gyp ERR! stack                                ^
2018-11-29T11:04:49.3164958Z gyp ERR! stack SyntaxError: invalid syntax
2018-11-29T11:04:49.3165226Z gyp ERR! stack 
2018-11-29T11:04:49.3166354Z gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
2018-11-29T11:04:49.3166782Z gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
2018-11-29T11:04:49.3167113Z gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
2018-11-29T11:04:49.3167639Z gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```
I'll take a look at what can be done about that.

**Pull request merged**
