### PR TITLE
watch worker script

### LINKED ISSUE #2: watch the worker script
Would you accept a PR that adds logic to watch the worker script and restart the cluster when the file changes?

Small change to [start.js](https://github.com/gja/cloudflare-worker-local/blob/master/start.js#L10):

```diff
  if (cluster.isMaster) {
+   require('chokidar')
+     .watch(process.argv[2], { ignoreInitial: true })
+     .on('change', () => cluster.disconnect());
    for (var i = 0; i < 4; i++) {
      cluster.fork();
    }
    cluster.on("exit", function(worker, code, signal) {
      console.log("worker " + worker.process.pid + " died");
      cluster.fork();
    });
  } else {
```

Could put this behind a `--watch` flag.

### PR DESCRIPTION
**Pull request by jdanyow**
fixes #2

### CODE REVIEW

**Comment by gja** [comment]
Closing this, as this can be done easily with `nodemon`

**Comment by jdanyow** [comment]
I think the technique I'm proposing will be much faster less likely to leave things in a bad state (especially when cache support is added).

For better nodemon support consider https://github.com/remy/nodemon#controlling-shutdown-of-your-script

**Comment by gja** [comment]
This script would also work (i'll update the readme). I suspect that KV support will have to go into a redis or something. The reason being 

```
cloudflare-worker-local sample-worker.js localhost:3000 4000 & nodemon --watch sample-worker.js --exec "kill -HUP $!"; kill $!
```

**Comment by gja** [comment]
I don't make any promises about working on zsh :-p

**Pull request closed without merging**
